# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\src\GUI_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ui.OpenGLWidget import OpenGLWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(943, 767)
        MainWindow.setStyleSheet("background-color: #242424;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, -50, 911, 771))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget.setMinimumSize(QtCore.QSize(900, 675))
        self.widget.setMaximumSize(QtCore.QSize(800, 600))
        self.widget.setStyleSheet("background-color: #000000; border-radius: 16px;")
        self.widget.setObjectName("widget")
        self.openGLWidget = OpenGLWidget(self.widget)
        self.openGLWidget.setGeometry(QtCore.QRect(10, 10, 880, 655))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openGLWidget.sizePolicy().hasHeightForWidth())
        self.openGLWidget.setSizePolicy(sizePolicy)
        self.openGLWidget.setMinimumSize(QtCore.QSize(880, 655))
        self.openGLWidget.setMaximumSize(QtCore.QSize(750, 550))
        self.openGLWidget.setStyleSheet("")
        self.openGLWidget.setObjectName("openGLWidget")
        self.speedometer = QtWidgets.QLCDNumber(self.widget)
        self.speedometer.setGeometry(QtCore.QRect(250, 540, 211, 81))
        self.speedometer.setStyleSheet("QLCDNumber {\n"
" color: #1fed45; \n"
"background-color: rgba(0, 0, 0, 50); \n"
"border-radius: 16px;\n"
"};\n"
"\n"
"")
        self.speedometer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.speedometer.setSmallDecimalPoint(False)
        self.speedometer.setDigitCount(5)
        self.speedometer.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.speedometer.setProperty("value", 888.8)
        self.speedometer.setObjectName("speedometer")
        self.l_km = QtWidgets.QLabel(self.widget)
        self.l_km.setGeometry(QtCore.QRect(470, 540, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.l_km.setFont(font)
        self.l_km.setStyleSheet(" color: #1fed45;\n"
"background-color: rgba(0, 0, 0, 50);\n"
"border-radius: 16px;")
        self.l_km.setObjectName("l_km")
        self.img_steer_left = QtWidgets.QLabel(self.widget)
        self.img_steer_left.setGeometry(QtCore.QRect(150, 540, 71, 71))
        self.img_steer_left.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.img_steer_left.setObjectName("img_steer_left")
        self.img_steer_right = QtWidgets.QLabel(self.widget)
        self.img_steer_right.setGeometry(QtCore.QRect(660, 540, 71, 71))
        self.img_steer_right.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.img_steer_right.setObjectName("img_steer_right")
        self.img_speed_limit = QtWidgets.QLabel(self.widget)
        self.img_speed_limit.setGeometry(QtCore.QRect(20, 489, 71, 71))
        self.img_speed_limit.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.img_speed_limit.setText("")
        self.img_speed_limit.setObjectName("img_speed_limit")
        self.img_back = QtWidgets.QLabel(self.widget)
        self.img_back.setGeometry(QtCore.QRect(660, 30, 211, 119))
        self.img_back.setMaximumSize(QtCore.QSize(470, 264))
        self.img_back.setObjectName("img_back")
        self.img_front = QtWidgets.QLabel(self.widget)
        self.img_front.setGeometry(QtCore.QRect(20, 30, 211, 119))
        self.img_front.setMinimumSize(QtCore.QSize(160, 90))
        self.img_front.setMaximumSize(QtCore.QSize(10000000, 10000000))
        self.img_front.setStyleSheet("")
        self.img_front.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.img_front.setFrameShadow(QtWidgets.QFrame.Plain)
        self.img_front.setObjectName("img_front")
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 943, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.l_km.setText(_translate("MainWindow", "km/h"))
        self.img_steer_left.setText(_translate("MainWindow", "TextLabel"))
        self.img_steer_right.setText(_translate("MainWindow", "TextLabel"))
        self.img_back.setText(_translate("MainWindow", "TextLabel"))
        self.img_front.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
